baseurl: "/Digikoppeling-Adapter-Intern"
apiname: "Digikoppeling Adapter Intern"
versie-nr: "1.2"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Digikoppeling Adapter Intern
    subnav:
      - title: Overzicht
        path: /
      - title: ICT aanbod
        path: /ICT aanbod  
      - title: Opdrachtgeverschap
        path: /Opdrachtgeverschap  
      - title: Documentatie  
        path: /Documentatie
#      - title: Werkgroep  
#        path: /Werkgroep 

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: melsk-r/jekyll-theme-vng-realisatie

github: VNG-Realisatie/Digikoppeling-Adapter-Intern

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/Digikoppeling-Adapter-Intern

standard_family: ZGW
